[package]
name = "orbit_simulation_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
num-traits = "0.2.18"
rand = "0.9.0-alpha.0"